name: skylens
description: Holografikus időjárás app
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  geolocator: ^10.1.0
  http: ^1.2.0

flutter:
  uses-material-design: true
